/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blueCarbonRegistrySol from './BlueCarbonRegistry.sol/index.js';
export type { blueCarbonRegistrySol };
import type * as carbonCreditNftSol from './CarbonCreditNFT.sol/index.js';
export type { carbonCreditNftSol };
export * as factories from './factories/index.js';
export type { BlueCarbonRegistry } from './BlueCarbonRegistry.sol/BlueCarbonRegistry.js';
export { BlueCarbonRegistry__factory } from './factories/BlueCarbonRegistry.sol/BlueCarbonRegistry__factory.js';
export type { CarbonCreditNFT } from './CarbonCreditNFT.sol/CarbonCreditNFT.js';
export { CarbonCreditNFT__factory } from './factories/CarbonCreditNFT.sol/CarbonCreditNFT__factory.js';