/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as blueCarbonRegistrySol from './BlueCarbonRegistry.sol/index.js';
export * as carbonCreditNftSol from './CarbonCreditNFT.sol/index.js';